exporter_port: 9158 # Port on which prometheus can call this exporter to get metrics
log_level: info
endpoints:  # you can define multiple endpoints even when they return different structures
  - json_data_url: http://stubonweb.herokuapp.com/kong-cluster-status # Url to get json data used for fetching metric values
    metric_name_prefix: kong_cluster_single # All metric names will be prefixed with this value
    metrics:
      - name: total_nodes # Final metric name will be kong_cluster_total_nodes
        description: Total number of nodes in kong cluster
        path: $.total
      - name: alive_nodes # Final metric name will be kong_cluster_alive_nodes
        description: Number of live nodes in kong cluster
        path: count($.data[@.status is "alive"])
  - json_data_urls: # OPTIONAL list to configure multiple data URLs separated by tag-label
      - url: http://stubonweb.herokuapp.com/kong-cluster-status # Url to get json data used for fetching metric values
        label: kong_cluster_1 # label value for label "tag"
      - url: http://stubonweb.herokuapp.com/kong-cluster-status # Url to get json data used for fetching metric values
        label: kong_cluster_2 # label value for label "tag"
    metric_name_prefix: kong_cluster_multiple # All metric names will be prefixed with this value
    metrics:
      - name: total_nodes # Final metric name will be kong_cluster_total_nodes
        description: Total number of nodes in kong cluster
        path: $.total
      - name: alive_nodes # Final metric name will be kong_cluster_alive_nodes
        description: Number of live nodes in kong cluster
        path: count($.data[@.status is "alive"])
